{% set version = '1.0-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-libcoin
  version: {{ version|replace("-", "_") }}

source:
  fn: libcoin_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/libcoin_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/libcoin/libcoin_{{ version }}.tar.gz
  sha256: 181b7f01b6568361e36ee242a96e20f0204ccdac3eba07294bddea822fd868c4

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mvtnorm
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mvtnorm

test:
  commands:
    - $R -e "library('libcoin')"           # [not win]
    - "\"%R%\" -e \"library('libcoin')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=libcoin
  license: GPL-2
  summary: Basic infrastructure for linear test statistics and permutation inference in the framework
    of Strasser and Weber (1999) <http://epub.wu.ac.at/102/>.  This package must not
    be used by end-users. CRAN package 'coin' implements all  user interfaces and is
    ready to be used by anyone.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
