travis:
  secure:
    BINSTAR_TOKEN: pwl+msxl/SUD0eJhS7M3oESNYNHuL76AVel0lcH4rp88rosokkF2KWjbA8ZGRfOS6XES/BdIh6lkwVpTcoJuLZpr8ZDA4pBe6iTimuAnP0tfOwR6RerTpqjEXFBBH5VxpQzLvEOWHRH5mxcXeSoZyfImJxHVBOdzU+JRP0ixy8EGXYRf1WbC/uXRvftcSsRi1p3C++1NA71GQPHX+OkNc6PRiROLgoSUweN7/ZN0+TBSCfJnNX0T60LEuN5m5w08l/F3jZZMnk1fXQ9235wr43232AcCheOJ91Ney6MDp7KZrQPR1IayPo9YZluDPhRynZHsr6dhh3UZaiy3tfPQjD8f0MN+pc9cVxPSNUY8uRYvWbOjT3Ztij+yNNYq8MeCSpRio33HkCeW/2l0dgADjfr8XZPXte87T5GRLd+hQ+iosXNs4zn/9fPqqJh0P8nM9pzoMd9rBNLCHYReA7CTy4vYTWeZjKD1bklR41wnEYNRSOF49erKFTojD3Dpbs68Kzq0GtpRIcL06Ue54tT51CbT7u2lvzbnFzGRN/L3oVR0Jzu7fCnzFsoUOK0AjXskzGrokHnga0HPrnAS8DpZETsHKDv6ZZzFu/hOA/UeLKvuydcCAEIN3FHwYfrZ5uGNlmpOP8YSRiQNaCRkfByaLatSlgS+maw2CE2ui8Rq4NA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
