travis:
  secure:
    BINSTAR_TOKEN: hoI0rluXuvhlxceKSbd7q91quMXRXCDkHjkfzrV5Ds8H2WnhQXi4QgrZxDzmDGlUdnrd8f5AuFtFeYdhqob/aDYuTXkj9V3h0fk4HupYMeVGbYsKVvCfCr+p4MlDLBpNjr7/E9b6H67dSialMcTEza0gB8XpH7HdnCjzbnZSbnb2iGnf50Df06GUagaKb/wb2vs0j7Hwm/CFMNXN522s3vrFVc4SwknQjxWEzrNxPiPc5wI9wrgNefeKM6tGiWM+7me6WRHUqS2V1ka6gpGC25NBXipMHdlCPZQh+JuH4KhTSBWlZaHO79TBDRnmLuALQ+zTIusuOf0a4dS05ztxkS8dJ+PUBsZV5AJ1Y4seKlRd35BOMnxTb1jQJaD96kGyMfQnJa6sOiSWcCMc3jBei4KH1G2IYp7ZLMi5vvcAjTD7QHxxIezyzT5hefShmuXGzfamj1t9NXCJTLr/KRkJgH6borcku4rpHqkoMRpG8ygjiZpKTNJCVvxyt2L3Q4U0jW9+Rjq4taUR4mf8S5i+oUBjY0eq4ifgDIPdupohXjq4laan9HFpcTNDzb0MfYNKE+U6Czt/UniB2emYEb1o/au3coEsmDbahfM5T/A1MhcNaDixOHxFTz3M3t6rlDwJuvTHiGFfgPBXSe+bL6UdjdNLb7gGve+GdJi+k3Y8pTE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
